SELECT id,
       worker_id,
       toli_id,
       employer_id,
       board_id,
       month,
       total_days,
       basic_wages,
       advance,
       gross_wages,
       levy,
       net_wages_payable,
       payment_type,
       txn_ref,
       receipt_nmbr,
       status_id
FROM worker_payments
